version: '2'

networks:
    bibbox-default-network:
      external: true
      
services:

  §§INSTANCE-negotiator:
    build:
       context: ./images/negotiator
    container_name:  §§INSTANCE-negotiator
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - §§INSTANCE-negotiator-db:negotiator-db
    ports:
      - "§§PORT:8080"
    depends_on:
      - §§INSTANCE-negotiator-db
      - §§INSTANCE-negotiator-data
    volumes_from: 
      - §§INSTANCE-negotiator-data
    environment:   
       DB_HOST: negotiator-db
       DB_NAME: negotiator
       DB_USER: saher
       DB_PASSWORD: saher

  §§INSTANCE-negotiator-db:
    image: postgres:9.6.5-alpine
    container_name:  §§INSTANCE-negotiator-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    environment:
      - POSTGRES_PASSWORD=saher
      - POSTGRES_USER=saher
      - POSTGRES_DB=negotiator 
    volumes_from: 
      - §§INSTANCE-negotiator-data
    depends_on:
      - §§INSTANCE-negotiator-data

  §§INSTANCE-negotiator-data:
    image: busybox
    container_name: §§INSTANCE-negotiator-data
    networks:
      - bibbox-default-network
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
